apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubcy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubcy
  template:
    metadata:
      labels:
        app: dubcy
    spec:
      containers:
      - name: dubcy
        image: 058264531143.dkr.ecr.us-west-2.amazonaws.com/goat
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dubcy
    k8s-app: dubcy
  name: dubcy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: dubcy
